
  CREATE TABLE "XE"."DIM_BRANCH" 
   (	"BRANCH_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"SRC_BRANCH_ID" VARCHAR2(70 BYTE), 
	"BRANCH_TYPE_CODE" VARCHAR2(70 BYTE), 
	"BRANCH_NAME" VARCHAR2(70 BYTE), 
	"BRANCH_DESC" VARCHAR2(70 BYTE), 
	"BRANCH_CONTACT_NAME" VARCHAR2(70 BYTE), 
	"BRANCH_CONTACT_PHONE" VARCHAR2(70 BYTE), 
	"BRANCH_CONTACT_EMAIL" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "DIM_BRANCH_UK1" UNIQUE ("SRC_BRANCH_ID", "LOAD_DATE", "LOAD_ID") DISABLE
   )PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )
