
  CREATE TABLE "XE"."FACT_CUSTOMER_SUMMARY_MONTHLY" 
   (	"CUSTOMER_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"YYYY_MM" VARCHAR2(30 BYTE), 
	"TOTAL_TRANS_COUNT" VARCHAR2(70 BYTE), 
	"TOTAL_TRANS_AMOUNT_USD" NUMBER(30,0), 
	"AVG_TRANS_AMOUNT" VARCHAR2(70 BYTE), 
	"MIN_AMOUNT" NUMBER(30,2), 
	"MAX_AMOUNT" NUMBER(30,2), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "FACT_CUSTOMER_SUMMARY_MONT_PK" PRIMARY KEY ("CUSTOMER_ID", "LOAD_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )
PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )
