
  CREATE TABLE "XE"."FACT_TRANSACTION" 
   (	"TRANSACTION_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"SRC_TRANSACTION_ID" VARCHAR2(70 BYTE), 
	"TRANSACTION_TYPE_ID" VARCHAR2(70 BYTE), 
	"TRANS_DATE_ID" NUMBER(30,0), 
	"BANK_ID" VARCHAR2(70 BYTE), 
	"BRANCH_ID" VARCHAR2(70 BYTE), 
	"CUSTOMER_ID" VARCHAR2(70 BYTE), 
	"ADDRESS_ID" VARCHAR2(70 BYTE), 
	"ACCOUNT_ID" VARCHAR2(70 BYTE), 
	"FROM_ACCOUNT" VARCHAR2(70 BYTE), 
	"TO_ACCOUNT" VARCHAR2(70 BYTE), 
	"AMOUNT_BASE_CURR" NUMBER(30,0), 
	"AMOUNT_USD" NUMBER(30,0), 
	"CURRENCY_CODE" VARCHAR2(70 BYTE), 
	"CURRENCY_RATE" NUMBER(30,0), 
	"NOTES" VARCHAR2(80 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0) NOT NULL ENABLE
   )
PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )




