
DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(
	
ADDRESS_ID STRING,
ADDRESS_LINE1 STRING,
ADDRESS_LINE2 STRING,
ADDRESS_LINE3 STRING,
CITY STRING,
COUNTY STRING,
STATE STRING,
ZIPCODE INT,
COUNTRY STRING,
LATITUDE STRING,
LONGITUDE STRING
)

PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
