
DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH(	

BRANCH_ID STRING,
BRANCH_TYPE_ID STRING,
BANK_ID STRING,
ADDRESS_ID STRING,
BRANCH_NAME STRING,
BRANCH_DESC STRING,
BRANCH_CONTACT_NAME STRING,
BRANCH_CONTACT_PHONE STRING,
BRANCH_CONTACT_EMAIL STRING
)
PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';

