DROP TABLE IF EXISTS DIM_STATE; 

CREATE TABLE DIM_STATE 
  ( 
     STATE_ID         STRING, 
     STATE_CODE       STRING, 
     STATE_NAME       STRING, 
     COUNTRY_CODE     STRING, 
     STATE_POPULATION INT 
  ) PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING) ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','; 