DROP TABLE IF EXISTS DIM_COUNTRY; 

CREATE TABLE DIM_COUNTRY 
  ( 
     COUNTRY_ID         STRING, 
     COUNTRY_CODE       STRING, 
     COUNTRY_NAME       STRING, 
     COUNTRY_POPULATION INT 
  ) PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING) ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',';