DROP TABLE IF EXISTS FACT_CUSTOMER_SUMMARY_MONTHLY; 

CREATE TABLE FACT_CUSTOMER_SUMMARY_MONTHLY 
  ( 
     CUSTOMER_ID            STRING, 
     YYYY_MM                STRING, 
     TOTAL_TRANS_COUNT      STRING, 
     TOTAL_TRANS_AMOUNT_USD INT, 
     AVG_TRANS_AMOUNT       INT, 
     MIN_AMOUNT             DECIMAL, 
     MAX_AMOUNT             DECIMAL 
  ) PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING) ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','; 