DROP TABLE IF EXISTS FACT_ACCOUNT_SUMMARY_MONTHLY; 

CREATE TABLE FACT_ACCOUNT_SUMMARY_MONTHLY 
  ( 
     ACCOUNT_ID             STRING, 
     YYYY_MM                STRING, 
     TOTAL_TRANS_COUNT      INT, 
     TOTAL_TRANS_AMOUNT_USD INT, 
     AVG_TRANS_AMOUNT       INT, 
     MIN_AMOUNT             DECIMAL, 
     MAX_AMOUNT             INT 
  ) PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING) ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',';