
DROP TABLE IF EXISTS HIVE_STREAM; 

CREATE TABLE HIVE_STREAM 
  ( 
     KYE        INT, 
     VALUE      STRING,
     TOPIC      STRING,
     PARTITION  INT,
     OFFSET     INT,
     TIMESTAMP  INT
  )  ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',';