
DROP TABLE IF EXISTS PRODUCT_TYPE;
CREATE TABLE PRODUCT_TYPE(	

PRODUCT_TYPE_ID STRING,
PRODUCT_TYPE_CODE STRING,
PRODUCT_TYPE_DESC STRING
)

PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
