DROP TABLE IF EXISTS TRANSACTION_TYPE; 

CREATE TABLE TRANSACTION_TYPE 
  ( 
     TRANSACTION_TYPE_ID   STRING, 
     TRANSACTION_TYPE_CODE STRING, 
     TRANSACTION_TYPE_DESC STRING 
  ) PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING) ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ','; 