DROP TABLE IF EXISTS CUSTOMER_IDIOSYNCRATIC_TRANSPOSE_STAGE; 

CREATE TABLE CUSTOMER_IDIOSYNCRATIC_TRANSPOSE_STAGE 
  ( 
     ITERATIONID INT, 
     CUSTOMER    STRING, 
     PD          DECIMAL, 
     VERSION     INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 