DROP TABLE IF EXISTS CUSTOMER_LOSS_SIMULATION; 

CREATE TABLE CUSTOMER_LOSS_SIMULATION 
  ( 
     CUST_ID        STRING, 
     ITERATIONID    INT, 
     CUSTOMER_LOSS  DECIMAL, 
     REPORTING_DATE STRING, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 
