
DROP TABLE IF EXISTS CUSTOMER_VAR_CONTRIBUTION_TOPN_PERC; 

CREATE TABLE CUSTOMER_VAR_CONTRIBUTION_TOPN_PERC 
  ( 
     REPORTING_DATE        STRING, 
     TOP_N                 STRING, 
     VAR_CONTRIBUTION_PERC DECIMAL, 
     VERSION               INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 
