
DROP TABLE IF EXISTS CUSTOMER_PORTFOLIO_UL_CALC_SUMMARY; 

CREATE TABLE CUSTOMER_PORTFOLIO_UL_CALC_SUMMARY 
  ( 
     CUST_ID                STRING, 
     PORTFOLIO_UL_CUST_SUM  DECIMAL, 
     PORTFOLIO_UL_TOTAL_SUM DECIMAL, 
     REPORTING_DATE         STRING, 
     VERSION                INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 
