DROP TABLE IF EXISTS CUSTOMER_PORTFOLIO; 

CREATE TABLE CUSTOMER_PORTFOLIO 
  ( 
     CUST_ID          STRING, 
     INDUSTRY         STRING, 
     PD               DECIMAL, 
     EXPOSURE         INT, 
     LGD              DECIMAL, 
     LGD_VAR          INT, 
     CORRELATION      DECIMAL, 
     SQRT_CORRELATION DECIMAL, 
     DEF_POINT        DECIMAL, 
     REPORTING_DATE   STRING, 
     VERSION          INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 