DROP TABLE IF EXISTS CUSTOMER_IDIOSYNCRATIC_TRANSPOSE; 

CREATE TABLE CUSTOMER_IDIOSYNCRATIC_TRANSPOSE 
  ( 
     ITERATIONID    INT, 
     REPORTING_DATE STRING, 
     CUSTOMER       STRING, 
     PD             DECIMAL, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 