
DROP TABLE IF EXISTS CUSTOMER_PORTFOLIO_UL_CALC_ALLOCATION; 

CREATE TABLE CUSTOMER_PORTFOLIO_UL_CALC_ALLOCATION 
  ( 
     CUST_ID                      STRING, 
     PORTFOLIO_UL_CUST_ALLOCATION DECIMAL, 
     REPORTING_DATE               STRING, 
     VERSION                      INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 