DROP TABLE IF EXISTS INDUSTRY_FACTOR_SIMULATION_STAGE; 

CREATE TABLE INDUSTRY_FACTOR_SIMULATION_STAGE 
  ( 
     ITERATION_ID INT, 
     FACTOR1      DECIMAL, 
     FACTOR2      DECIMAL, 
     FACTOR3      DECIMAL, 
     FACTOR4      DECIMAL, 
     VERSION      INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 