DROP TABLE IF EXISTS INDUSTRY_FACTOR_CORRELATION_TRANSPOSE; 

CREATE TABLE INDUSTRY_FACTOR_CORRELATION_TRANSPOSE 
  ( 
     FACTOR_X       STRING, 
     REPORTING_DATE STRING, 
     FACTOR_Y       STRING, 
     FACTOR_VALUE   DECIMAL, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 