
DROP TABLE IF EXISTS INDUSTRY_FACTOR_TRANSPOSE; 

CREATE TABLE INDUSTRY_FACTOR_TRANSPOSE 
  ( 
     ITERATION_ID   INT, 
     REPORTING_DATE STRING, 
     FACTOR         STRING, 
     FACTOR_VALUE   DECIMAL, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 
