DROP TABLE IF EXISTS INDUSTRY_FACTOR_MEAN; 

CREATE TABLE INDUSTRY_FACTOR_MEAN 
  ( 
     ID             STRING, 
     MEAN           DECIMAL, 
     REPORTING_DATE STRING, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 
