
DROP TABLE IF EXISTS PORTFOLIO_LOSS_SIMULATION_EL; 

CREATE TABLE PORTFOLIO_LOSS_SIMULATION_EL 
  ( 
     ITERATIONID      INT, 
     PORTFOLIO_LOSS   DECIMAL, 
     EXPECTED_LOSS    DECIMAL, 
     VALUE_AT_RISK    DECIMAL, 
     ECONOMIC_CAPITAL DECIMAL, 
     REPORTING_DATE   STRING, 
     VERSION          INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 