
DROP TABLE IF EXISTS PORTFOLIO_LOSS_SIMULATION; 

CREATE TABLE PORTFOLIO_LOSS_SIMULATION 
  ( 
     ITERATIONID    INT, 
     PORTFOLIO_LOSS DECIMAL, 
     REPORTING_DATE STRING, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 