
DROP TABLE IF EXISTS PORTFOLIO_LOSS_HISTOGRAM_PERCENTAGE; 

CREATE TABLE PORTFOLIO_LOSS_HISTOGRAM_PERCENTAGE 
  ( 
     REPORTING_DATE STRING, 
     BUCKET         STRING, 
     FREQUENCY      INT, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','; 
