DROP TABLE IF EXISTS PORTFOLIO_EXPECTED_SUM; 

CREATE TABLE PORTFOLIO_EXPECTED_SUM 
  ( 
     EXPECTED_SUM   DECIMAL, 
     REPORTING_DATE STRING, 
     VERSION        INT 
  ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';