CREATE TABLE edw_small.account
(
  account_id VARCHAR(50) NOT NULL,
  account_type_id integer,
  account_status_id integer,
  product_type_id integer,
  customer_id VARCHAR(50),
  pin_number integer,
  nationality VARCHAR(50),
  primary_iden_doc VARCHAR(50),
  primary_iden_doc_id VARCHAR(50),
  secondary_iden_doc VARCHAR(50),
  secondary_iden_doc_id VARCHAR(50),
  account_open_date VARCHAR(50),
  account_number VARCHAR(50),
  opening_balance VARCHAR(50),
  current_balance VARCHAR(50),
  overdue_balance integer,
  overdue_date VARCHAR(50),
  currency_code VARCHAR(50),
  interest_type VARCHAR(50),
  interest_rate double precision,
  load_date VARCHAR(50) NOT NULL,
  load_id integer,
  CONSTRAINT account_pkey PRIMARY KEY (account_id,load_date,load_id)
);
