
DROP TABLE EDW_SMALL.account_status_type;
CREATE TABLE EDW_SMALL.account_status_type(	ACCOUNT_STATUS_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	ACCOUNT_STATUS_CODE VARCHAR(10),
	ACCOUNT_STATUS_DESC VARCHAR(500),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER, 
CONSTRAINT ACCOUNT_STATUS_ID_PK  PRIMARY KEY(ACCOUNT_STATUS_ID,LOAD_DATE,LOAD_ID));
