
DROP TABLE EDW_SMALL.branch_type;
CREATE TABLE EDW_SMALL.branch_type(	BRANCH_TYPE_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	BRANCH_TYPE_CODE VARCHAR(10),
	BRANCH_TYPE_DESC VARCHAR(500),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER, 
CONSTRAINT BRANCH_TYPE_ID_PK  PRIMARY KEY(BRANCH_TYPE_ID,LOAD_DATE,LOAD_ID));
