
CREATE TABLE edw_small.dim_date
(
  date_id integer NOT NULL,
  date_type VARCHAR(50),
  date_val VARCHAR(50),
  day_num_of_week integer,
  day_num_of_month integer,
  day_num_of_quarter integer,
  day_num_of_year integer,
  day_num_absolute integer,
  day_of_week_name VARCHAR(50),
  day_of_week_abbreviation VARCHAR(50),
  julian_day_num_of_year integer,
  julian_day_num_absolute integer,
  is_weekday VARCHAR(50),
  is_usa_civil_holiday VARCHAR(50),
  is_last_day_of_week VARCHAR(50),
  is_last_day_of_month VARCHAR(50),
  is_last_day_of_quarter VARCHAR(50),
  is_last_day_of_year VARCHAR(50),
  is_last_day_of_fiscal_month VARCHAR(50),
  is_last_day_of_fiscal_quarter VARCHAR(50),
  is_last_day_of_fiscal_year VARCHAR(50),
  week_of_year_begin_date VARCHAR(50),
  week_of_year_begin_date_key integer,
  week_of_year_end_date VARCHAR(50),
  week_of_year_end_date_key integer,
  week_of_month_begin_date VARCHAR(50),
  week_of_month_begin_date_key integer,
  week_of_month_end_date VARCHAR(50),
  week_of_month_end_date_key integer,
  week_of_quarter_begin_date VARCHAR(50),
  week_of_quarter_begin_date_key integer,
  week_of_quarter_end_date VARCHAR(50),
  week_of_quarter_end_date_key integer,
  week_num_of_month integer,
  week_num_of_quarter integer,
  week_num_of_year integer,
  month_num_of_year integer,
  month_num_overall VARCHAR(50),
  month_name VARCHAR(50),
  month_name_abbreviation VARCHAR(50),
  month_begin_date VARCHAR(50),
  month_begin_date_key integer,
  month_end_date VARCHAR(50),
  month_end_date_key integer,
  quarter_num_of_year integer,
  quarter_num_overall integer,
  quarter_begin_date VARCHAR(50),
  quarter_begin_date_key integer,
  quarter_end_date VARCHAR(50),
  quarter_end_date_key integer,
  year_num integer,
  year_begin_date VARCHAR(50),
  year_begin_date_key integer,
  year_end_date VARCHAR(50),
  year_end_date_key integer,
  yyyy_mm VARCHAR(50),
  yyyy_mm_dd VARCHAR(50),
  dd_mon_yyyy VARCHAR(50),
  load_date VARCHAR(50) NOT NULL,
  load_id integer NOT NULL,
  CONSTRAINT dim_date_pkey PRIMARY KEY (date_id),
  CONSTRAINT date_val UNIQUE (date_val, load_date)
);

