DROP TABLE IF EXISTS DIM_ACCOUNT; 

CREATE TABLE IF EXISTS DIM_ACCOUNT 
  ( 
     ACCOUNT_ID            VARCHAR(50) DEFAULT 0 NOT NULL,
     SRC_ACCOUNT_ID        VARCHAR(50),
     ACCOUNT_TYPE_CODE     VARCHAR(10),
     ACCOUNT_STATUS_CODE   VARCHAR(10),
     PRODUCT_TYPE_CODE     VARCHAR(10),
     PIN_NUMBER            INTEGER,
     NATIONALITY           VARCHAR(100),
     PRIMARY_IDEN_DOC      VARCHAR(100),
     PRIMARY_IDEN_DOC_ID   VARCHAR(50),
     SECONDARY_IDEN_DOC    VARCHAR(100),
     SECONDARY_IDEN_DOC_ID VARCHAR(50),
     ACCOUNT_OPEN_DATE     VARCHAR(10),
     ACCOUNT_NUMBER        VARCHAR(50),
     OPENING_BALANCE       INTEGER,
     CURRENT_BALANCE       INTEGER,
     OVERDUE_BALANCE       INTEGER,
     OVERDUE_DATE          VARCHAR(10),
     CURRENCY_CODE         VARCHAR(10),
     INTEREST_TYPE         VARCHAR(50),
     INTEREST_RATE         DECIMAL(10,2),
     LOAD_DATE             VARCHAR(10),
     LOAD_ID               INTEGER,
     CONSTRAINT ACCOUNT_ID_DIM_PK PRIMARY KEY(ACCOUNT_ID) 
  ); 