DROP TABLE IF EXISTS edw_small.FACT_ACCOUNT_SUMMARY_MONTHLY; 

CREATE TABLE edw_small.FACT_ACCOUNT_SUMMARY_MONTHLY 
  ( 
     ACCOUNT_ID             VARCHAR(50) DEFAULT 0 NOT NULL,
     YYYY_MM                VARCHAR(50) DEFAULT 0 NOT NULL,
     TOTAL_TRANS_COUNT      INTEGER,
     TOTAL_TRANS_AMOUNT_USD INTEGER,
     AVG_TRANS_AMOUNT       INTEGER,
     MIN_AMOUNT             DECIMAL(10,2),
     MAX_AMOUNT             INTEGER,
     LOAD_DATE              VARCHAR(10),
     LOAD_ID                INTEGER,
     CONSTRAINT ACCOUNT_ID_FACT_PK PRIMARY KEY(ACCOUNT_ID,YYYY_MM) 
  );
