
DROP TABLE EDW_SMALL.fact_customer_summary_monthly;
CREATE TABLE EDW_SMALL.fact_customer_summary_monthly(	CUSTOMER_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	YYYY_MM VARCHAR(50) DEFAULT 0 NOT NULL,
	TOTAL_TRANS_COUNT VARCHAR(50),
	TOTAL_TRANS_AMOUNT_USD INTEGER,
	AVG_TRANS_AMOUNT INTEGER,
	MIN_AMOUNT DECIMAL(10,2),
	MAX_AMOUNT DECIMAL(10,2),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER, 
CONSTRAINT CUSTOMER_ID_PK  PRIMARY KEY(CUSTOMER_ID,LOAD_DATE,LOAD_ID));
