DROP TABLE IF EXISTS FACT_CUSTOMER_SUMMARY_MONTHLY; 

CREATE TABLE IF EXISTS FACT_CUSTOMER_SUMMARY_MONTHLY 
  ( 
     CUSTOMER_ID            VARCHAR(50) DEFAULT 0 NOT NULL,
     YYYY_MM                VARCHAR(50) DEFAULT 0 NOT NULL,
     TOTAL_TRANS_COUNT      VARCHAR(50),
     TOTAL_TRANS_AMOUNT_USD INTEGER,
     AVG_TRANS_AMOUNT       INTEGER,
     MIN_AMOUNT             DECIMAL(10,2),
     MAX_AMOUNT             DECIMAL(10,2),
     LOAD_DATE              VARCHAR(10),
     LOAD_ID                INTEGER,
     CONSTRAINT CUSTOMER_ID_FACT_PK PRIMARY KEY(CUSTOMER_ID) 
  );