DROP TABLE IF EXISTS MODEL_TRAINING_SET; 
CREATE TABLE MODEL_TRAINING_SET
(
  CUSTOMER_ID INTEGER NOT NULL,
  ADDRESS_ID INTEGER NOT NULL,
  BRANCH_ID INTEGER NOT NULL,
  COMMUTE_DISTANCE_MILES INTEGER NOT NULL,
  LABEL INTEGER NOT NULL,
  CENSOR INTEGER NOT NULL,
  VERSION INTEGER NOT NULL
);

