DROP TABLE EDW_SMALL.product_type;
CREATE TABLE EDW_SMALL.product_type(	PRODUCT_TYPE_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	PRODUCT_TYPE_CODE VARCHAR(10),
	PRODUCT_TYPE_DESC VARCHAR(500),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER, 
CONSTRAINT LOAD_ID_PK  PRIMARY KEY(PRODUCT_TYPE_ID,LOAD_DATE,LOAD_ID));
