DROP TABLE IF EXISTS TARGET_SIM_LINEAR_REGRESSION;
CREATE TABLE TARGET_SIM_LINEAR_REGRESSION (
  ID INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  INTEREST_RATE DOUBLE PRECISION,
  ACCOUNT_TYPE_ID DOUBLE PRECISION,
  ACCOUNT_STATUS_ID DOUBLE PRECISION
);
