DROP TABLE IF EXISTS TARGET_SIM_LINEAR_REGRESSION;
CREATE TABLE TARGET_SIM_MULTIVARIENT_NORMAL_DIS (
  ID INTEGER NOT NULL,
  INTERESTRATE DOUBLE PRECISION,
  COL2 DOUBLE PRECISION,
  COL3 DOUBLE PRECISION,
  VERSION INTEGER NOT NULL  
);
