OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/app/aml/data/csv/noheader/fact_transaction_journal.csv'
TRUNCATE
INTO TABLE FACT_TRANSACTION_JOURNAL
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(TRANSACTION_ID,DIRECTION,ACCOUNT_ID,CUSTOMER_ID,TRANSACTION_TYPE_CODE,TRANSACTION_DATE
,TRANSACTION_COUNTRY,SENDER_COUNTRY,RECIEVER_COUNTRY,AMOUNT_USD,LOAD_DATE,LOAD_ID)
