DROP TABLE ACCOUNT_STATUS_TYPE;
CREATE TABLE ACCOUNT_STATUS_TYPE 
  ( 
     ACCOUNT_STATUS_ID   VARCHAR2(50) NOT NULL, 
     ACCOUNT_STATUS_CODE VARCHAR2(10), 
     ACCOUNT_STATUS_DESC VARCHAR2(500), 
     LOAD_DATE           VARCHAR2(10), 
     LOAD_ID             INTEGER, 
     CONSTRAINT ACCOUNT_STATUS_TYPE_PK PRIMARY KEY (ACCOUNT_STATUS_ID) 
  ); 
