create table "account" 
   (
   	"account_id" varchar2(70 byte) not null enable, 
	"account_type_id" number(30,0), 
	"account_status_id" number(30,0), 
	"product_type_id" number(30,0), 
	"customer_id" varchar2(70 byte), 
	"pin_number" number(30,0), 
	"nationality" varchar2(70 byte), 
	"primary_iden_doc" varchar2(70 byte), 
	"primary_iden_doc_id" varchar2(70 byte), 
	"secondary_iden_doc" varchar2(70 byte), 
	"secondary_iden_doc_id" varchar2(70 byte), 
	"account_open_date" varchar2(70 byte), 
	"account_number" varchar2(70 byte), 
	"opening_balance" varchar2(70 byte), 
	"current_balance" varchar2(70 byte), 
	"overdue_balance" number(30,0), 
	"overdue_date" varchar2(70 byte), 
	"currency_code" varchar2(70 byte), 
	"interest_type" varchar2(70 byte), 
	"interest_rate" float(50), 
	"load_date" varchar2(70 byte) not null enable,
	"load_id" number(30,0), 
	 constraint "account_pk" primary key ("account_id", "load_date", "load_id")
);
