 CREATE TABLE "ACCOUNT_TYPE" 
   (
   	"ACCOUNT_TYPE_ID" NUMBER(30,0) DEFAULT 0 NOT NULL ENABLE, 
	"ACCOUNT_TYPE_CODE" VARCHAR2(70 BYTE), 
	"ACCOUNT_TYPE_DESC" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE,
	"LOAD_ID" NUMBER(30,0) DEFAULT 0, 
	 CONSTRAINT "ACCOUNT_TYPE_PK" PRIMARY KEY ("ACCOUNT_TYPE_ID", "LOAD_DATE")
);


exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/ACCOUNT_TYPE.ctl
