 CREATE TABLE "ACCOUNT_STATUS_TYPE" 
   (
   	"ACCOUNT_STATUS_ID" NUMBER(30,0) DEFAULT 0 NOT NULL ENABLE, 
	"ACCOUNT_STATUS_CODE" VARCHAR2(70 BYTE), 
	"ACCOUNT_STATUS_DESC" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE,
	"LOAD_ID" NUMBER(30,0) DEFAULT 0, 
	 CONSTRAINT "ACCOUNT_STATUS_TYPE_PK" PRIMARY KEY ("ACCOUNT_STATUS_ID", "LOAD_DATE")
);


exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/ACCOUNT_STATUS_TYPE.ctl
