DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT 
  ( 
     ACCOUNT_ID            VARCHAR2(50) NOT NULL, 
     ACCOUNT_TYPE_ID       VARCHAR2(50), 
     ACCOUNT_STATUS_ID     VARCHAR2(50), 
     PRODUCT_TYPE_ID       VARCHAR2(50), 
     CUSTOMER_ID           VARCHAR2(50), 
     PIN_NUMBER            INTEGER, 
     NATIONALITY           VARCHAR2(50), 
     PRIMARY_IDEN_DOC      VARCHAR2(50), 
     PRIMARY_IDEN_DOC_ID   VARCHAR2(50), 
     SECONDARY_IDEN_DOC    VARCHAR2(50), 
     SECONDARY_IDEN_DOC_ID VARCHAR2(50), 
     ACCOUNT_OPEN_DATE     VARCHAR2(10), 
     ACCOUNT_NUMBER        VARCHAR2(50), 
     OPENING_BALANCE       INTEGER, 
     CURRENT_BALANCE       INTEGER, 
     OVERDUE_BALANCE       INTEGER, 
     OVERDUE_DATE          VARCHAR2(10), 
     CURRENCY_CODE         VARCHAR2(10), 
     INTEREST_TYPE         VARCHAR2(10), 
     INTEREST_RATE         DECIMAL(10, 2), 
     LOAD_DATE             VARCHAR2(10), 
     LOAD_ID               INTEGER, 
     CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID) 
  ); 
