
CREATE TABLE ACCOUNT_TYPE 
  ( 
     ACCOUNT_TYPE_ID   VARCHAR2(50) NOT NULL, 
     ACCOUNT_TYPE_CODE VARCHAR2(10), 
     ACCOUNT_TYPE_DESC VARCHAR2(500), 
     LOAD_DATE         VARCHAR2(10), 
     LOAD_ID           INTEGER, 
     CONSTRAINT ACCOUNT_TYPE_PK PRIMARY KEY (ACCOUNT_TYPE_ID) 
  ); 
