CREATE TABLE "ADDRESS" 
   (
   	"ADDRESS_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"ADDRESS_LINE1" VARCHAR2(70 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(70 BYTE), 
	"ADDRESS_LINE3" VARCHAR2(70 BYTE), 
	"CITY" VARCHAR2(70 BYTE), 
	"COUNTY" VARCHAR2(70 BYTE), 
	"STATE" VARCHAR2(70 BYTE), 
	"ZIPCODE" VARCHAR2(70 BYTE),
	"COUNTRY" VARCHAR2(70 BYTE), 
	"LATITUDE" VARCHAR2(70 BYTE), 
	"LONGITUDE" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE,
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID", "LOAD_DATE")
   );

