DROP TABLE BANK;
CREATE TABLE BANK 
  ( 
     BANK_ID             VARCHAR2(50) NOT NULL, 
     BANK_CODE           VARCHAR2(10), 
     BANK_NAME           VARCHAR2(100), 
     BANK_ACCOUNT_NUMBER VARCHAR2(50), 
     BANK_CURRENCY_CODE  VARCHAR2(10), 
     BANK_CHECK_DIGITS   INTEGER, 
     LOAD_DATE           VARCHAR2(10), 
     LOAD_ID             INTEGER, 
     CONSTRAINT BANK_PK PRIMARY KEY (BANK_ID) 
  ); 
