CREATE TABLE "BRANCH_TYPE" 
   (
   	"BRANCH_TYPE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"BRANCH_TYPE_CODE" VARCHAR2(70 BYTE), 
	"BRANCH_TYPE_DESC" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0) DEFAULT 0, 
	 CONSTRAINT "BRANCH_TYPE_PK" PRIMARY KEY ("BRANCH_TYPE_ID", "LOAD_DATE") DISABLE
);

exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/BRANCH_TYPE.ctl
