CREATE TABLE "BRANCH" 
   (	"BRANCH_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"BRANCH_TYPE_ID" NUMBER(20,0), 
	"BANK_ID" VARCHAR2(70 BYTE), 
	"ADDRESS_ID" VARCHAR2(70 BYTE), 
	"BRANCH_NAME" VARCHAR2(70 BYTE), 
	"BRANCH_DESC" VARCHAR2(70 BYTE), 
	"BRANCH_CONTACT_NAME" VARCHAR2(70 BYTE), 
	"BRANCH_CONTACT_PHONE" VARCHAR2(70 BYTE), 
	"BRANCH_CONTACT_EMAIL" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE,
	"LOAD_ID" NUMBER(30,0)
);



exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/BRANCH.ctl
