CREATE TABLE "CUSTOMER" 
   (
   	"CUSTOMER_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"ADDRESS_ID" VARCHAR2(70 BYTE), 
	"BRANCH_ID" NUMBER(30,0), 
	"TITLE" VARCHAR2(70 BYTE), 
	"FIRST_NAME" VARCHAR2(70 BYTE), 
	"MIDDLE_NAME" VARCHAR2(70 BYTE), 
	"LAST_NAME" VARCHAR2(70 BYTE), 
	"SSN" VARCHAR2(70 BYTE), 
	"PHONE" VARCHAR2(70 BYTE), 
	"DATE_FIRST_PURCHASE" VARCHAR2(70 BYTE), 
	"COMMUTE_DISTANCE_MILES" NUMBER(30,0), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID", "LOAD_DATE")
)


exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/CUSTOMER.ctl
