DROP TABLE DIM_CUSTOMER;
CREATE TABLE DIM_CUSTOMER 
  ( 
     CUSTOMER_ID         VARCHAR2(50) NOT NULL, 
     SRC_CUSTOMER_ID     VARCHAR2(50), 
     TITLE               VARCHAR2(100), 
     FIRST_NAME          VARCHAR2(100), 
     MIDDLE_NAME         VARCHAR2(100), 
     LAST_NAME           VARCHAR2(100), 
     ADDRESS_LINE1       VARCHAR2(50), 
     ADDRESS_LINE2       VARCHAR2(50), 
     PHONE               VARCHAR2(50), 
     DATE_FIRST_PURCHASE VARCHAR2(10), 
     COMMUTE_DISTANCE    INTEGER, 
     CITY                VARCHAR2(100), 
     STATE               VARCHAR2(100), 
     POSTAL_CODE         VARCHAR2(10), 
     COUNTRY             VARCHAR2(100), 
     LOAD_DATE           VARCHAR2(10), 
     LOAD_ID             INTEGER, 
     CONSTRAINT DIM_CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID) 
  ); 
