
CREATE TABLE DIM_BRANCH 
  ( 
     BRANCH_ID            VARCHAR2(50) NOT NULL, 
     SRC_BRANCH_ID        VARCHAR2(50), 
     BRANCH_TYPE_CODE     VARCHAR2(10), 
     BRANCH_NAME          VARCHAR2(100), 
     BRANCH_DESC          VARCHAR2(500), 
     BRANCH_CONTACT_NAME  VARCHAR2(100), 
     BRANCH_CONTACT_PHONE VARCHAR2(100), 
     BRANCH_CONTACT_EMAIL VARCHAR2(100), 
     LOAD_DATE            VARCHAR2(10), 
     LOAD_ID              INTEGER, 
     CONSTRAINT DIM_BRANCH_PK PRIMARY KEY (BRANCH_ID) 
  ); 
