CREATE TABLE "DIM_STATE" 
   (
   	"STATE_CODE" VARCHAR2(70 BYTE) , 
	"STATE_NAME" VARCHAR2(70 BYTE), 
   	"COUNTRY_CODE" VARCHAR2(70 BYTE) , 
	"STATE_POPULATION"  NUMBER(30,0), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "DIM_STATE_PK" PRIMARY KEY ("STATE_CODE", "LOAD_DATE")
);


