create table "dim_date" 
   (
   	"date_id" number(30,0), 
	"date_type" varchar2(70 byte), 
	"date_val" varchar2(70 byte), 
	"day_num_of_week" number(30,0), 
	"day_num_of_month" number(30,0), 
	"day_num_of_quarter" number(30,0), 
	"day_num_of_year" number(30,0), 
	"day_num_absolute" number(30,0), 
	"day_of_week_name" varchar2(70 byte), 
	"day_of_week_abbreviation" varchar2(70 byte), 
	"julian_day_num_of_year" number(30,0), 
	"julian_day_num_absolute" number(30,0), 
	"is_weekday" varchar2(70 byte), 
	"is_usa_civil_holiday" varchar2(70 byte), 
	"is_last_day_of_week" varchar2(70 byte), 
	"is_last_day_of_month" varchar2(70 byte), 
	"is_last_day_of_quarter" varchar2(70 byte), 
	"is_last_day_of_year" varchar2(70 byte), 
	"is_last_day_of_fiscal_month" varchar2(70 byte), 
	"is_last_day_of_fiscal_quarter" varchar2(70 byte), 
	"is_last_day_of_fiscal_year" varchar2(70 byte), 
	"week_of_year_begin_date" varchar2(70 byte), 
	"week_of_year_begin_date_key" number(30,0), 
	"week_of_year_end_date" varchar2(70 byte), 
	"week_of_year_end_date_key" number(30,0), 
	"week_of_month_begin_date" varchar2(70 byte), 
	"week_of_month_begin_date_key" number(30,0), 
	"week_of_month_end_date" varchar2(70 byte), 
	"week_of_month_end_date_key" number(30,0), 
	"week_of_quarter_begin_date" varchar2(70 byte), 
	"week_of_quarter_begin_date_key" number(30,0), 
	"week_of_quarter_end_date" varchar2(70 byte), 
	"week_of_quarter_end_date_key" number(30,0), 
	"week_num_of_month" number(30,0), 
	"week_num_of_quarter" number(30,0), 
	"week_num_of_year" number(30,0), 
	"month_num_of_year" number(30,0), 
	"month_num_overall" varchar2(70 byte), 
	"month_name" varchar2(70 byte), 
	"month_name_abbreviation" varchar2(70 byte), 
	"month_begin_date" varchar2(70 byte), 
	"month_begin_date_key" number(30,0), 
	"month_end_date" varchar2(70 byte), 
	"month_end_date_key" number(30,0), 
	"quarter_num_of_year" number(30,0), 
	"quarter_num_overall" number(30,0), 
	"quarter_begin_date" varchar2(70 byte), 
	"quarter_begin_date_key" number(30,0), 
	"quarter_end_date" varchar2(70 byte), 
	"quarter_end_date_key" number(30,0), 
	"year_num" number(30,0), 
	"year_begin_date" varchar2(70 byte), 
	"year_begin_date_key" number(30,0), 
	"year_end_date" varchar2(70 byte), 
	"year_end_date_key" number(30,0), 
	"yyyy_mm" varchar2(70 byte), 
	"yyyy_mm_dd" varchar2(70 byte), 
	"dd_mon_yyyy" varchar2(70 byte),
	"load_date" varchar2(70 byte) not null enable, 
	"load_id" number(30,0) not null enable, 
	constraint "date_id_pk" primary key ("date_id", "load_id", "load_date"),
    constraint "date_val_uk" unique ("date_val", "load_date", "load_id")
   );