DROP TABLE DIM_STATE;
CREATE TABLE DIM_STATE 
  ( 
     STATE_ID         VARCHAR2(50) NOT NULL, 
     STATE_CODE       VARCHAR2(10), 
     STATE_NAME       VARCHAR2(100), 
     COUNTRY_CODE     VARCHAR2(10), 
     STATE_POPULATION INTEGER, 
     LOAD_DATE        VARCHAR2(10), 
     LOAD_ID          INTEGER, 
     CONSTRAINT DIM_STATE_PK PRIMARY KEY (STATE_ID) 
  ); 
