CREATE TABLE "DIM_ACCOUNT" 
   (
   	"ACCOUNT_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"SRC_ACCOUNT_ID" VARCHAR2(70 BYTE), 
	"ACCOUNT_TYPE_CODE" VARCHAR2(70 BYTE), 
	"ACCOUNT_STATUS_CODE" VARCHAR2(70 BYTE), 
	"PRODUCT_TYPE_CODE" VARCHAR2(70 BYTE), 
	"PIN_NUMBER" NUMBER(30,0), 
	"NATIONALITY" VARCHAR2(70 BYTE), 
	"PRIMARY_IDEN_DOC" VARCHAR2(70 BYTE), 
	"PRIMARY_IDEN_DOC_ID" VARCHAR2(70 BYTE), 
	"SECONDARY_IDEN_DOC" VARCHAR2(70 BYTE), 
	"SECONDARY_IDEN_DOC_ID" VARCHAR2(70 BYTE), 
	"ACCOUNT_OPEN_DATE" VARCHAR2(70 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(70 BYTE), 
	"OPENING_BALANCE" VARCHAR2(70 BYTE), 
	"CURRENT_BALANCE" VARCHAR2(70 BYTE), 
	"OVERDUE_BALANCE" NUMBER(30,0), 
	"OVERDUE_DATE" VARCHAR2(70 BYTE), 
	"CURRENCY_CODE" VARCHAR2(70 BYTE), 
	"INTEREST_TYPE" VARCHAR2(70 BYTE), 
	"INTEREST_RATE" FLOAT(50), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0) NOT NULL ENABLE, 
	 CONSTRAINT "DIM_ACCOUNT_PK" PRIMARY KEY ("ACCOUNT_ID", "LOAD_DATE", "LOAD_ID")
);

exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/dim_account.ctl
