CREATE TABLE "DIM_COUNTRY" 
   (
   	"COUNTRY_CODE" VARCHAR2(70 BYTE) , 
	"COUNTRY_NAME" VARCHAR2(70 BYTE), 
	"COUNTRY_POPULATION"  NUMBER(30,0), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "DIM_COUNTRY_PK" PRIMARY KEY ("COUNTRY_CODE", "LOAD_DATE")
);
