CREATE TABLE "DIM_ADDRESS" 
   (
   	"ADDRESS_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"SRC_ADDRESS_ID" VARCHAR2(70 BYTE), 
	"ADDRESS_LINE1" VARCHAR2(70 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(70 BYTE), 
	"ADDRESS_LINE3" VARCHAR2(70 BYTE), 
	"CITY" VARCHAR2(70 BYTE), 
	"COUNTY" VARCHAR2(70 BYTE), 
	"STATE" VARCHAR2(70 BYTE), 
	"ZIPCODE" NUMBER(30,0), 
	"COUNTRY" VARCHAR2(70 BYTE), 
	"LATITUDE" VARCHAR2(70 BYTE), 
	"LONGTITUDE" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"LOAD_ID" NUMBER(30,0) DEFAULT 0, 
	 CONSTRAINT "DIM_ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID", "LOAD_DATE")
 );
