
CREATE TABLE DIM_ACCOUNT 
  ( 
     ACCOUNT_ID            VARCHAR2(50) NOT NULL, 
     SRC_ACCOUNT_ID        VARCHAR2(50), 
     ACCOUNT_TYPE_CODE     VARCHAR2(10), 
     ACCOUNT_STATUS_CODE   VARCHAR2(10), 
     PRODUCT_TYPE_CODE     VARCHAR2(10), 
     PIN_NUMBER            INTEGER, 
     NATIONALITY           VARCHAR2(100), 
     PRIMARY_IDEN_DOC      VARCHAR2(100), 
     PRIMARY_IDEN_DOC_ID   VARCHAR2(50), 
     SECONDARY_IDEN_DOC    VARCHAR2(100), 
     SECONDARY_IDEN_DOC_ID VARCHAR2(50), 
     ACCOUNT_OPEN_DATE     VARCHAR2(10), 
     ACCOUNT_NUMBER        VARCHAR2(50), 
     OPENING_BALANCE       INTEGER, 
     CURRENT_BALANCE       INTEGER, 
     OVERDUE_BALANCE       INTEGER, 
     OVERDUE_DATE          VARCHAR2(10), 
     CURRENCY_CODE         VARCHAR2(10), 
     INTEREST_TYPE         VARCHAR2(50), 
     INTEREST_RATE         DECIMAL(10, 2), 
     LOAD_DATE             VARCHAR2(10), 
     LOAD_ID               INTEGER, 
     CONSTRAINT DIM_ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID) 
  ); 

