 CREATE TABLE "INFERYX"."DIM_TRANSACTION_TYPE" 
   (	"TRANSACTION_TYPE_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE,
  "SRC_TRANSACTION_TYPE_ID"  VARCHAR2(70 BYTE) NOT NULL,
  "TRANSACTION_TYPE_CODE" VARCHAR2(70 BYTE) NOT NULL,
  "TRANSACTION_TYPE_DESC" VARCHAR2(70 BYTE) NOT NULL,
  "LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL,
  "LOAD_ID" NUMBER(30,0),
	 CONSTRAINT "DIM_TRANSACTION_TYPE_PK" PRIMARY KEY ("TRANSACTION_TYPE_ID", "LOAD_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )

