DROP TABLE DIM_COUNTRY;
CREATE TABLE DIM_COUNTRY 
  ( 
     COUNTRY_CODE       VARCHAR2(10), 
     COUNTRY_NAME       VARCHAR2(100), 
     COUNTRY_POPULATION INTEGER, 
     COUNTRY_RISK_LEVEL INTEGER,
     LOAD_DATE          VARCHAR2(10), 
     LOAD_ID            INTEGER
  ); 
