CREATE TABLE "DIM_TRANSACTION_TYPE" 
   (
  "TRANSACTION_TYPE_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE,
  "SRC_TRANSACTION_TYPE_ID"  VARCHAR2(70 BYTE) NOT NULL,
  "TRANSACTION_TYPE_CODE" VARCHAR2(70 BYTE) NOT NULL,
  "TRANSACTION_TYPE_DESC" VARCHAR2(70 BYTE) NOT NULL,
  "LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL,
  "LOAD_ID" NUMBER(30,0)
);

