DROP TABLE FACT_TRANSACTION;
CREATE TABLE FACT_TRANSACTION 
  ( 
     TRANSACTION_ID      VARCHAR2(50) NOT NULL, 
     SRC_TRANSACTION_ID  VARCHAR2(50), 
     TRANSACTION_TYPE_ID INTEGER, 
     TRANS_DATE_ID       INTEGER, 
     BANK_ID             INTEGER, 
     BRANCH_ID           INTEGER, 
     CUSTOMER_ID         VARCHAR2(50), 
     ADDRESS_ID          VARCHAR2(50), 
     ACCOUNT_ID          VARCHAR2(50), 
     FROM_ACCOUNT        VARCHAR2(50), 
     TO_ACCOUNT          VARCHAR2(50), 
     AMOUNT_BASE_CURR    INTEGER, 
     AMOUNT_USD          INTEGER, 
     CURRENCY_CODE       VARCHAR2(10), 
     CURRENCY_RATE       INTEGER, 
     NOTES               VARCHAR2(50), 
     LOAD_DATE           VARCHAR2(10), 
     LOAD_ID             INTEGER, 
     CONSTRAINT FACT_TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID) 
  ); 
