DROP TABLE FACT_ACCOUNT_SUMMARY_MONTHLY;
CREATE TABLE FACT_ACCOUNT_SUMMARY_MONTHLY 
  ( 
     ACCOUNT_ID             VARCHAR2(50) NOT NULL, 
     YYYY_MM                VARCHAR2(50) NOT NULL, 
     TOTAL_TRANS_COUNT      INTEGER, 
     TOTAL_TRANS_AMOUNT_USD INTEGER, 
     AVG_TRANS_AMOUNT       INTEGER, 
     MIN_AMOUNT             DECIMAL(10, 2), 
     MAX_AMOUNT             INTEGER, 
     LOAD_DATE              VARCHAR2(10), 
     LOAD_ID                INTEGER, 
     CONSTRAINT FACT_ACCOUNT_SUMMARY_MONTHLY_PK PRIMARY KEY (ACCOUNT_ID) 
  ); 
