DROP TABLE MODEL_TRAINING_SET;
CREATE TABLE MODEL_TRAINING_SET
(
  CUSTOMER_ID 			INTEGER,
  ADDRESS_ID 			INTEGER,
  BRANCH_ID 			INTEGER,
  COMMUTE_DISTANCE_MILES INTEGER,
  LABEL 				INTEGER,
  CENSOR 				INTEGER,
  VERSION 				INTEGER
);
