
CREATE TABLE PRODUCT_TYPE 
  ( 
     PRODUCT_TYPE_ID   VARCHAR2(50) NOT NULL, 
     PRODUCT_TYPE_CODE VARCHAR2(10), 
     PRODUCT_TYPE_DESC VARCHAR2(500), 
     LOAD_DATE         VARCHAR2(10), 
     LOAD_ID           INTEGER 
  ); 
