
CREATE TABLE TRANSACTION 
  ( 
     TRANSACTION_ID      VARCHAR2(50) NOT NULL, 
     TRANSACTION_TYPE_ID VARCHAR2(50), 
     ACCOUNT_ID          VARCHAR2(50), 
     TRANSACTION_DATE    VARCHAR2(10), 
     FROM_ACCOUNT        VARCHAR2(50), 
     TO_ACCOUNT          VARCHAR2(50), 
     AMOUNT_BASE_CURR    DECIMAL(10, 2), 
     AMOUNT_USD          DECIMAL(10, 2), 
     CURRENCY_CODE       VARCHAR2(10), 
     CURRENCY_RATE       DECIMAL(10, 2), 
     NOTES               VARCHAR2(100), 
     LOAD_DATE           VARCHAR2(10), 
     LOAD_ID             INTEGER, 
     CONSTRAINT TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID) 
  ); 
