CREATE TABLE "TRANSACTION_TYPE" 
   (
   	"TRANSACTION_TYPE_ID" VARCHAR2(70 BYTE), 
	"TRANSACTION_TYPE_CODE" VARCHAR2(70 BYTE), 
	"TRANSACTION_TYPE_DESC" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE), 
	"LOAD_ID" NUMBER(30,0)   
   );
