DROP TABLE equity_orders; 

CREATE TABLE equity_orders
  ( 
     order_identifier                        INTEGER, 
     order_event_number                      INTEGER, 
     order_placement_date                    VARCHAR2(50), 
     parent_order_id                         INTEGER, 
     parent_order_placement_date             VARCHAR2(50), 
     root_order_identifier                   VARCHAR2(50), 
     root_order_placement_date               VARCHAR2(50), 
     order_allocation_relationship_code      VARCHAR2(50), 
     allocated_order_id                      INTEGER, 
     allocated_order_placement_date          VARCHAR2(50), 
     order_event_type_cd                     VARCHAR2(50), 
     order_event_date                        VARCHAR2(50), 
     order_event_time                        VARCHAR2(50), 
     firm_identifier                         VARCHAR2(50), 
     originator_identifier                   VARCHAR2(50), 
     originator_system                       VARCHAR2(50), 
     originating_organization_identifier     VARCHAR2(50), 
     submission_channel                      VARCHAR2(50), 
     automated_channel                       VARCHAR2(50), 
     solicited_indicator                     VARCHAR2(50), 
     order_management_date                   VARCHAR2(50), 
     order_management_time                   VARCHAR2(50), 
     source_market_participant_identifier    VARCHAR2(50), 
     receiving_desk_identifier               VARCHAR2(50), 
     order_received_date                     VARCHAR2(50), 
     order_received_time                     VARCHAR2(50), 
     buyer_or_seller_identifier              VARCHAR2(50), 
     buyer_or_seller_account_identifier      VARCHAR2(50), 
     buyer_or_seller_type                    VARCHAR2(50), 
     buyer_or_seller_organization_identifier VARCHAR2(50), 
     buy_or_sell_code                        VARCHAR2(50), 
     seller_position_code                    VARCHAR2(50), 
     customer_accounting_rule                VARCHAR2(50), 
     customer_position                       VARCHAR2(50), 
     security_identifier                     VARCHAR2(50), 
     security_short_name                     VARCHAR2(50), 
     isin_identifier                         VARCHAR2(50), 
     product_category                        VARCHAR2(50), 
     product_type                            VARCHAR2(50), 
     product_subtype                         VARCHAR2(50), 
     structured_deal                         VARCHAR2(50), 
     order_type_code                         VARCHAR2(50), 
     limit_price_issuing                     DECIMAL(10, 2), 
     limit_price_base                        DECIMAL(10, 2), 
     stop_price_issuing                      DECIMAL(10, 2), 
     stop_price_base                         DECIMAL(10, 2), 
     unit_quantity                           DECIMAL(10, 2), 
     time_in_force                           VARCHAR2(50), 
     expiration_date                         VARCHAR2(50), 
     expiration_time                         VARCHAR2(50), 
     held_indicator                          VARCHAR2(50), 
     do_not_display                          VARCHAR2(50), 
     order_handling_code1                    VARCHAR2(50), 
     order_handling_code2                    VARCHAR2(50), 
     order_handling_code3                    VARCHAR2(50), 
     order_handling_code4                    VARCHAR2(50), 
     order_handling_code5                    VARCHAR2(50), 
     dnr_dni_instructions                    VARCHAR2(50), 
     trade_along_side_consent_code           VARCHAR2(50), 
     trade_along_side_ratio_code             VARCHAR2(50), 
     detailed_instructions                   VARCHAR2(50), 
     ipo_indicator                           VARCHAR2(50), 
     new_issue_indicator                     VARCHAR2(50), 
     issuer_repurchase                       VARCHAR2(50), 
     program_trading                         VARCHAR2(50), 
     arbitrage_indicator                     VARCHAR2(50), 
     destination_market                      VARCHAR2(50), 
     routed_unit_quantity                    DECIMAL(10, 2), 
     bunched_order                           VARCHAR2(50), 
     canceling_party_role                    VARCHAR2(50), 
     cancellation_reason                     VARCHAR2(50), 
     replaced_order_identifier               VARCHAR2(50), 
     replaced_order_placement_date           VARCHAR2(50), 
     business_domain                         VARCHAR2(50), 
     jurisdiction                            VARCHAR2(50), 
     source_system                           VARCHAR2(50),
	 PRIMARY KEY(order_identifier,order_event_number)     
  );
