DROP TABLE IF EXISTS equity_executions; 

CREATE TABLE equity_executions
  ( 
     trade_execution_identifier              INTEGER, 
     trade_execution_event_number            INTEGER, 
     trade_execution_event_type_code         VARCHAR2(50), 
     trade_execution_date                    VARCHAR2(50), 
     trade_execution_time                    VARCHAR2(50), 
     trade_execution_event_date              VARCHAR2(50), 
     trade_execution_event_time              VARCHAR2(50), 
     trade_allocation_relationship_code      VARCHAR2(50), 
     allocated_trade_execution_id            INTEGER, 
     allocated_trade_execution_date          VARCHAR2(50), 
     trade_purpose                           VARCHAR2(50), 
     firm_identifier                         VARCHAR2(50), 
     originator_identifier                   VARCHAR2(50), 
     originator_system                       VARCHAR2(50), 
     originating_organization_identifier     VARCHAR2(50), 
     submission_channel                      VARCHAR2(50), 
     automated_channel                       VARCHAR2(50), 
     solicited_indicator                     VARCHAR2(50), 
     system_entry_date                       VARCHAR2(50), 
     system_entry_time                       VARCHAR2(50), 
     trade_approval_indicator                VARCHAR2(50), 
     buyer_identifier                        VARCHAR2(50), 
     buyer_account_identifier                VARCHAR2(50), 
     buyer_type_code                         VARCHAR2(50), 
     buyer_organization                      VARCHAR2(50), 
     seller_identifier                       VARCHAR2(50), 
     seller_account                          VARCHAR2(50), 
     seller_type_code                        VARCHAR2(50), 
     seller_organization                     VARCHAR2(50), 
     seller_position_code                    VARCHAR2(50), 
     customer_accounting                     VARCHAR2(50), 
     customer_position                       VARCHAR2(50), 
     security_identifier                     VARCHAR2(50), 
     security_short_name                     VARCHAR2(50), 
     isin_identifier                         VARCHAR2(50), 
     product_category                        VARCHAR2(50), 
     product_type                            VARCHAR2(50), 
     product_subtype                         VARCHAR2(50), 
     market_identifier                       VARCHAR2(50), 
     unit_quantity                           DECIMAL(10, 2), 
     price_issuing                           DECIMAL(10, 2), 
     price_base                              DECIMAL(10, 2), 
     trade_execution_currency                VARCHAR2(50), 
     principal_amount_issuing                DECIMAL(10, 2), 
     principal_amount_base                   DECIMAL(10, 2), 
     yield_percentage                        DECIMAL(10, 2), 
     yield_method_code                       VARCHAR2(50), 
     agent_identifier                        VARCHAR2(50), 
     executing_desk_identifier               VARCHAR2(50), 
     executing_sub_desk_identifier           VARCHAR2(50), 
     executing_desk_country_code             VARCHAR2(50), 
     trading_account                         VARCHAR2(50), 
     trader_position                         VARCHAR2(50), 
     trader_position_code                    VARCHAR2(50), 
     commission_amount_issuing               DECIMAL(10, 2), 
     commission_amount_base                  DECIMAL(10, 2), 
     mutual_fund_load_fee_issuing            VARCHAR2(50), 
     mutual_fund_load_fee_base               VARCHAR2(50), 
     riskless_principal_indicator            VARCHAR2(50), 
     riskless_principal_reference_identifier VARCHAR2(50), 
     settlement_date                         VARCHAR2(50), 
     nonstandard_settlement_indicator        VARCHAR2(50), 
     settlement_type                         VARCHAR2(50), 
     settlement_currency                     VARCHAR2(50), 
     settlement_instruction                  VARCHAR2(50), 
     order_identifier                        INTEGER, 
     order_placement_date                    VARCHAR2(50), 
     order_execution_sequence_number         VARCHAR2(50), 
     source_system_order_remaining_unit_qty  VARCHAR2(50), 
     structured_deal                         VARCHAR2(50), 
     ipo_indicator                           VARCHAR2(50), 
     new_issue_indicator                     VARCHAR2(50), 
     replaced_trade_execution_identifier     VARCHAR2(50), 
     replaced_trade_execution_date           VARCHAR2(50), 
     cancellation_or_correction_reason       VARCHAR2(50), 
     business_domain                         VARCHAR2(50), 
     jurisdiction                            VARCHAR2(50), 
     source_system                           VARCHAR2(50),
	 PRIMARY KEY(trade_execution_identifier,trade_execution_event_number)     
  ); 
