OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/upload/account_type.csv'
TRUNCATE
INTO TABLE ACCOUNT_TYPE
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
 (	ACCOUNT_TYPE_ID ,
	ACCOUNT_TYPE_CODE , 
	ACCOUNT_TYPE_DESC , 
	LOAD_DATE , 
	LOAD_ID 
  ) 
