 OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/upload/address.csv'
TRUNCATE
INTO TABLE ADDRESS
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
 (	ADDRESS_ID , 
	ADDRESS_LINE1 , 
	ADDRESS_LINE2 , 
	ADDRESS_LINE3 , 
	CITY , 
	COUNTY , 
	STATE , 
	ZIPCODE ,
	COUNTRY , 
	LATITUDE , 
	LONGITUDE , 
	LOAD_DATE , 
	LOAD_ID
   )
