OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/upload/bank.csv'
TRUNCATE
INTO TABLE BANK
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
 (	BANK_ID , 
	BANK_CODE , 
	BANK_NAME , 
	BANK_ACCOUNT_NUMBER , 
	BANK_CURRENCY_CODE , 
	BANK_CHECK_DIGITS ,
	LOAD_DATE , 
	LOAD_ID 
   ) 
