OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/app/edw/data/csv/noheader/branch.csv'
TRUNCATE
INTO TABLE BRANCH
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(	BRANCH_ID ,
	BRANCH_TYPE_ID ,
	BANK_ID , 
	ADDRESS_ID , 
	BRANCH_NAME , 
	BRANCH_DESC , 
	BRANCH_CONTACT_NAME , 
	BRANCH_CONTACT_PHONE , 
	BRANCH_CONTACT_EMAIL , 
	LOAD_DATE , 
	LOAD_ID
   ) 
