OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/app/edw/data/csv/noheader/customer.csv'
TRUNCATE
INTO TABLE CUSTOMER
FIELDS TERMINATED BY ','
TRAILING NULLCOLS 
(	CUSTOMER_ID , 
	ADDRESS_ID , 
	BRANCH_ID ,
	TITLE , 
	FIRST_NAME , 
	MIDDLE_NAME , 
	LAST_NAME , 
	SSN , 
	PHONE , 
	DATE_FIRST_PURCHASE , 
	COMMUTE_DISTANCE_MILES ,
	LOAD_DATE , 
	LOAD_ID
   ) 
