OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/app/edw/data/csv/noheader/dim_country.csv'
TRUNCATE
INTO TABLE DIM_COUNTRY
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
 (	 COUNTRY_CODE, 
     COUNTRY_NAME, 
     COUNTRY_POPULATION, 
     COUNTRY_RISK_LEVEL,
     LOAD_DATE, 
     LOAD_ID
   ) 
