
OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/upload/transaction.csv'
TRUNCATE
INTO TABLE TRANSACTION
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(TRANSACTION_ID,TRANSACTION_TYPE_ID,ACCOUNT_ID,TRANSACTION_DATE,FROM_ACCOUNT,TO_ACCOUNT,AMOUNT_BASE_CURR,AMOUNT_USD,CURRENCY_CODE,CURRENCY_RATE ,NOTES,LOAD_DATE,LOAD_ID)