OPTIONS (DIRECT=TRUE, ERRORS=50, rows=1000000)
UNRECOVERABLE
LOAD DATA
INFILE '/user/hive/warehouse/framework/upload/transaction_type.csv'
TRUNCATE
INTO TABLE TRANSACTION_TYPE
FIELDS TERMINATED BY ','
TRAILING NULLCOLS 
(	TRANSACTION_TYPE_ID ,
	TRANSACTION_TYPE_CODE , 
	TRANSACTION_TYPE_DESC , 
	LOAD_DATE , 
	LOAD_ID 
   ) 
