 drop table if exists account_summary_daily;
create table account_summary_daily
( 
	    customer_id varchar(50), 
	    account_id varchar(50) , 
	    trans_start_date varchar(50) , 
	    trans_end_date varchar(50), 
	    day_num varchar(50) , 
        in_wire_transfers_trans_count  integer(50) , 
        in_wire_transfers_trans_amount_usd  decimal(10,0) , 
        out_wire_transfers_trans_count  integer(50) , 
        out_wire_transfers_trans_amount_usd  decimal(10,0) , 
        net_wire_transfers_trans_count  integer(50) , 
        net_wire_transfers_trans_amount_usd  decimal(10,0) , 
        in_cash_transfers_trans_count  integer(50) , 
        in_cash_transfers_trans_amount_usd  decimal(10,0) , 
        out_cash_transfers_trans_count  integer(50) , 
        out_cash_transfers_trans_amount_usd  decimal(10,0) , 
        net_cash_transfers_trans_count  integer(50) , 
        net_cash_transfers_trans_amount_usd  decimal(10,0) , 
        all_wire_transfers_round_amount_usd  decimal(10,0) , 
        all_cash_transfers_round_amount_usd  decimal(10,0) , 
        all_cash_transfers_round_amount_count  integer(50) , 
        all_wire_transfers_round_amount_count  integer(50) , 
        all_cash_transfers_trans_count  integer(50) , 
        all_wire_transfers_trans_count  integer(50) , 
        in_cash_transfers_trans_amount_min  decimal(10,0) , 
        out_wire_transfers_trans_amount_min  decimal(10,0) , 
        all_wire_transfers_round_amount_min  decimal(10,0) , 
        all_cash_transfers_round_amount_min  decimal(10,0) , 
        in_wire_transfers_trans_amount_min  decimal(10,0) , 
        out_cash_transfers_trans_amount_min  decimal(10,0) , 
        all_cash_transfers_round_amount_max  decimal(10,0) , 
        all_wire_transfers_round_amount_max  decimal(10,0) , 
        in_wire_transfers_trans_amount_max  decimal(10,0) , 
        in_cash_transfers_trans_amount_max  decimal(10,0) , 
        out_wire_transfers_trans_amount_max  decimal(10,0) , 
        out_cash_transfers_trans_amount_max  decimal(10,0) , 
        all_wire_transfers_round_amount_avg  decimal(10,0) , 
        all_cash_transfers_round_amount_avg  decimal(10,0) , 
        in_wire_transfers_trans_amount_avg  decimal(10,0) , 
        in_cash_transfers_trans_amount_avg  decimal(10,0) , 
        out_wire_transfers_trans_amount_avg  decimal(10,0) , 
        out_cash_transfers_trans_amount_avg  decimal(10,0) , 
        all_cash_transfers_round_amount_stddev  decimal(10,0) , 
        in_cash_transfers_trans_amount_stddev  decimal(10,0) , 
        out_cash_transfers_trans_amount_stddev  decimal(10,0) , 
        all_wire_transfers_round_amount_stddev  decimal(10,0) , 
        in_wire_transfers_trans_amount_stddev  decimal(10,0) , 
        out_wire_transfers_trans_amount_stddev  decimal(10,0) , 
        in_cash_transfers_round_amount_count  integer(50) , 
        in_wire_transfers_round_amount_count  integer(50) , 
        out_wire_transfers_round_amount_count  integer(50) , 
        out_cash_transfers_round_amount_count  integer(50) , 
        out_cash_transfers_round_amount_sum  decimal(10,0) , 
        out_wire_transfers_round_amount_sum  decimal(10,0) , 
        in_wire_transfers_round_amount_sum  decimal(10,0) , 
        in_cash_transfers_round_amount_sum  decimal(10,0)   
  );
