SELECT TABNAME,CNT FROM
(
SELECT 'FACT_TRANSACTION_JOURNAL' AS TABNAME, COUNT(*) AS CNT FROM FACT_TRANSACTION_JOURNAL
UNION
SELECT 'CUSTOMER_ALERT_SUMMARY' AS TABNAME, COUNT(*) AS CNT FROM CUSTOMER_ALERT_SUMMARY
UNION
SELECT 'RULE_ALERT_SUMMARY' AS TABNAME, COUNT(*) AS CNT FROM RULE_ALERT_SUMMARY
UNION
SELECT 'RULE_ALERT_SUMMARY' AS TABNAME, COUNT(*) AS CNT FROM RULE_ALERT_SUMMARY
UNION
SELECT 'PREDICT_SUSPICIOUS_ACTIVITY_GBT' AS TABNAME, COUNT(*) AS CNT FROM PREDICT_SUSPICIOUS_ACTIVITY_GBT
UNION
SELECT 'PREDICT_SUSPICIOUS_ACTIVITY_LR' AS TABNAME, COUNT(*) AS CNT FROM PREDICT_SUSPICIOUS_ACTIVITY_LR
) T1
ORDER BY TABNAME;
