DROP TABLE IF EXISTS predict_suspicious_activity_gbt;

CREATE TABLE predict_suspicious_activity_gbt 
  ( 
     label                                  INTEGER(50), 
     in_wire_transfers_trans_count          INTEGER(50), 
     in_wire_transfers_trans_amount_usd     DECIMAL(10, 3), 
     out_wire_transfers_trans_count         INTEGER(50), 
     out_wire_transfers_trans_amount_usd    DECIMAL(10, 3), 
     net_wire_transfers_trans_count         INTEGER(50), 
     net_wire_transfers_trans_amount_usd    DECIMAL(10, 3), 
     in_cash_transfers_trans_count          INTEGER(50), 
     in_cash_transfers_trans_amount_usd     DECIMAL(10, 3), 
     out_cash_transfers_trans_count         INTEGER(50), 
     out_cash_transfers_trans_amount_usd    DECIMAL(10, 3), 
     net_cash_transfers_trans_count         INTEGER(50), 
     net_cash_transfers_trans_amount_usd    DECIMAL(10, 3), 
     all_wire_transfers_round_amount_usd    DECIMAL(10, 3), 
     all_cash_transfers_round_amount_usd    DECIMAL(10, 3), 
     all_cash_transfers_round_amount_count  INTEGER(50), 
     all_wire_transfers_round_amount_count  INTEGER(50), 
     all_cash_transfers_trans_count         INTEGER(50), 
     all_wire_transfers_trans_count         INTEGER(50), 
     in_cash_transfers_trans_amount_min     DECIMAL(10, 3), 
     out_wire_transfers_trans_amount_min    DECIMAL(10, 3), 
     all_wire_transfers_round_amount_min    DECIMAL(10, 3), 
     all_cash_transfers_round_amount_min    DECIMAL(10, 3), 
     in_wire_transfers_trans_amount_min     DECIMAL(10, 3), 
     out_cash_transfers_trans_amount_min    DECIMAL(10, 3), 
     all_cash_transfers_round_amount_max    DECIMAL(10, 3), 
     all_wire_transfers_round_amount_max    DECIMAL(10, 3), 
     in_wire_transfers_trans_amount_max     DECIMAL(10, 3), 
     in_cash_transfers_trans_amount_max     DECIMAL(10, 3), 
     out_wire_transfers_trans_amount_max    DECIMAL(10, 3), 
     out_cash_transfers_trans_amount_max    DECIMAL(10, 3), 
     all_wire_transfers_round_amount_avg    DECIMAL(10, 3), 
     all_cash_transfers_round_amount_avg    DECIMAL(10, 3), 
     in_wire_transfers_trans_amount_avg     DECIMAL(10, 3), 
     in_cash_transfers_trans_amount_avg     DECIMAL(10, 3), 
     out_wire_transfers_trans_amount_avg    DECIMAL(10, 3), 
     out_cash_transfers_trans_amount_avg    DECIMAL(10, 3), 
     all_cash_transfers_round_amount_stddev DECIMAL(10, 3), 
     in_cash_transfers_trans_amount_stddev  DECIMAL(10, 3), 
     out_cash_transfers_trans_amount_stddev DECIMAL(10, 3), 
     all_wire_transfers_round_amount_stddev DECIMAL(10, 3), 
     in_wire_transfers_trans_amount_stddev  DECIMAL(10, 3), 
     out_wire_transfers_trans_amount_stddev DECIMAL(10, 3), 
     in_cash_transfers_round_amount_count   INTEGER(50), 
     in_wire_transfers_round_amount_count   INTEGER(50), 
     out_wire_transfers_round_amount_count  INTEGER(50), 
     out_cash_transfers_round_amount_count  INTEGER(50), 
     out_cash_transfers_round_amount_sum    DECIMAL(10, 3), 
     out_wire_transfers_round_amount_sum    DECIMAL(10, 3), 
     in_wire_transfers_round_amount_sum     DECIMAL(10, 3), 
     in_cash_transfers_round_amount_sum     DECIMAL(10, 3), 
     features                               VARCHAR(50), 
     rawprediction                          VARCHAR(50), 
     probability                            VARCHAR(50), 
     prediction                             DECIMAL(10, 3) 
  ); 

