drop table if exists predict_suspicious_activity_gbt;

create table predict_suspicious_activity_gbt 
  ( 
     label                                  integer(50), 
     in_wire_transfers_trans_count          integer(50), 
     in_wire_transfers_trans_amount_usd     decimal(10, 3), 
     out_wire_transfers_trans_count         integer(50), 
     out_wire_transfers_trans_amount_usd    decimal(10, 3), 
     net_wire_transfers_trans_count         integer(50), 
     net_wire_transfers_trans_amount_usd    decimal(10, 3), 
     in_cash_transfers_trans_count          integer(50), 
     in_cash_transfers_trans_amount_usd     decimal(10, 3), 
     out_cash_transfers_trans_count         integer(50), 
     out_cash_transfers_trans_amount_usd    decimal(10, 3), 
     net_cash_transfers_trans_count         integer(50), 
     net_cash_transfers_trans_amount_usd    decimal(10, 3), 
     all_wire_transfers_round_amount_usd    decimal(10, 3), 
     all_cash_transfers_round_amount_usd    decimal(10, 3), 
     all_cash_transfers_round_amount_count  integer(50), 
     all_wire_transfers_round_amount_count  integer(50), 
     all_cash_transfers_trans_count         integer(50), 
     all_wire_transfers_trans_count         integer(50), 
     in_cash_transfers_trans_amount_min     decimal(10, 3), 
     out_wire_transfers_trans_amount_min    decimal(10, 3), 
     all_wire_transfers_round_amount_min    decimal(10, 3), 
     all_cash_transfers_round_amount_min    decimal(10, 3), 
     in_wire_transfers_trans_amount_min     decimal(10, 3), 
     out_cash_transfers_trans_amount_min    decimal(10, 3), 
     all_cash_transfers_round_amount_max    decimal(10, 3), 
     all_wire_transfers_round_amount_max    decimal(10, 3), 
     in_wire_transfers_trans_amount_max     decimal(10, 3), 
     in_cash_transfers_trans_amount_max     decimal(10, 3), 
     out_wire_transfers_trans_amount_max    decimal(10, 3), 
     out_cash_transfers_trans_amount_max    decimal(10, 3), 
     all_wire_transfers_round_amount_avg    decimal(10, 3), 
     all_cash_transfers_round_amount_avg    decimal(10, 3), 
     in_wire_transfers_trans_amount_avg     decimal(10, 3), 
     in_cash_transfers_trans_amount_avg     decimal(10, 3), 
     out_wire_transfers_trans_amount_avg    decimal(10, 3), 
     out_cash_transfers_trans_amount_avg    decimal(10, 3), 
     all_cash_transfers_round_amount_stddev decimal(10, 3), 
     in_cash_transfers_trans_amount_stddev  decimal(10, 3), 
     out_cash_transfers_trans_amount_stddev decimal(10, 3), 
     all_wire_transfers_round_amount_stddev decimal(10, 3), 
     in_wire_transfers_trans_amount_stddev  decimal(10, 3), 
     out_wire_transfers_trans_amount_stddev decimal(10, 3), 
     in_cash_transfers_round_amount_count   integer(50), 
     in_wire_transfers_round_amount_count   integer(50), 
     out_wire_transfers_round_amount_count  integer(50), 
     out_cash_transfers_round_amount_count  integer(50), 
     out_cash_transfers_round_amount_sum    decimal(10, 3), 
     out_wire_transfers_round_amount_sum    decimal(10, 3), 
     in_wire_transfers_round_amount_sum     decimal(10, 3), 
     in_cash_transfers_round_amount_sum     decimal(10, 3), 
     features                               varchar(500), 
     rawprediction                          varchar(50), 
     probability                            varchar(50), 
     prediction                             decimal(10, 3) 
  ); 
