DROP TABLE IF EXISTS PREDICT_SUSPICIOUS_ACTIVITY_LR;

CREATE TABLE PREDICT_SUSPICIOUS_ACTIVITY_LR 
(
  LABEL INTEGER(50),
  FEATURES VARCHAR(50), 
  RAWPREDICTION VARCHAR(50), 
  PROBABILITY VARCHAR(50), 
  PREDICTION DECIMAL(10,3));
