DROP TABLE IF EXISTS RULE_ALERT_SUMMARY;

CREATE TABLE RULE_ALERT_SUMMARY
( 
  RULE_TYPE VARCHAR(50),
  FOCUS_TYPE VARCHAR(50),
  ALERTED INTEGER(50), 
  NON_ALERTED INTEGER(50), 
  BUSINESS_DATE VARCHAR(50)
);


