DROP TABLE ACCOUNT_STATUS_TYPE;
CREATE TABLE ACCOUNT_STATUS_TYPE(	
	ACCOUNT_STATUS_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	ACCOUNT_STATUS_CODE VARCHAR(10),
	ACCOUNT_STATUS_DESC VARCHAR(500),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT ACCOUNT_STATUS_ID_PK  PRIMARY KEY(ACCOUNT_STATUS_ID,LOAD_DATE,LOAD_ID));
 ALTER TABLE ACCOUNT_STATUS_TYPE PARTITION BY KEY(LOAD_DATE,LOAD_ID);