SELECT TABNAME,CNT FROM
(
SELECT 'ACCOUNT_MYSQL' AS TABNAME, COUNT(*) AS CNT FROM ACCOUNT_MYSQL
UNION
SELECT 'ACCOUNT' AS TABNAME, COUNT(*) AS CNT FROM ACCOUNT
UNION
SELECT 'ACCOUNT_STATUS_TYPE' AS TABNAME, COUNT(*) AS CNT FROM ACCOUNT_STATUS_TYPE
UNION
SELECT 'ACCOUNT_TYPE' AS TABNAME, COUNT(*) AS CNT FROM ACCOUNT_TYPE
UNION
SELECT 'ADDRESS' AS TABNAME, COUNT(*) AS CNT FROM ADDRESS
UNION
SELECT 'BANK' AS TABNAME, COUNT(*) AS CNT FROM BANK
UNION
SELECT 'BRANCH' AS TABNAME, COUNT(*) AS CNT FROM BRANCH
UNION
SELECT 'BRANCH_TYPE' AS TABNAME, COUNT(*) AS CNT FROM BRANCH_TYPE
UNION
SELECT 'CUSTOMER' AS TABNAME, COUNT(*) AS CNT FROM CUSTOMER
UNION
SELECT 'DIM_DATE' AS TABNAME, COUNT(*) AS CNT FROM DIM_DATE
UNION
SELECT 'PRODUCT_TYPE' AS TABNAME, COUNT(*) AS CNT FROM PRODUCT_TYPE
UNION
SELECT 'TRANSACTION' AS TABNAME, COUNT(*) AS CNT FROM TRANSACTION
UNION
SELECT 'TRANSACTION_TYPE' AS TABNAME, COUNT(*) AS CNT FROM TRANSACTION_TYPE
UNION
SELECT 'DIM_ACCOUNT' AS TABNAME, COUNT(*) AS CNT FROM DIM_ACCOUNT
UNION
SELECT 'DIM_ADDRESS' AS TABNAME, COUNT(*) AS CNT FROM DIM_ADDRESS
UNION
SELECT 'DIM_BANK' AS TABNAME, COUNT(*) AS CNT FROM DIM_BANK
UNION
SELECT 'DIM_BRANCH' AS TABNAME, COUNT(*) AS CNT FROM DIM_BRANCH
UNION
SELECT 'DIM_COUNTRY' AS TABNAME, COUNT(*) AS CNT FROM DIM_COUNTRY
UNION
SELECT 'DIM_CUSTOMER' AS TABNAME, COUNT(*) AS CNT FROM DIM_CUSTOMER
UNION
SELECT 'DIM_TRANSACTION_TYPE' AS TABNAME, COUNT(*) AS CNT FROM DIM_TRANSACTION_TYPE
UNION
SELECT 'DP_RULE_RESULTS' AS TABNAME, COUNT(*) AS CNT FROM DP_RULE_RESULTS
UNION
SELECT 'DQ_RULE_RESULTS' AS TABNAME, COUNT(*) AS CNT FROM DQ_RULE_RESULTS
UNION
SELECT 'FACT_ACCOUNT_SUMMARY_MONTHLY' AS TABNAME, COUNT(*) AS CNT FROM FACT_ACCOUNT_SUMMARY_MONTHLY
UNION
SELECT 'FACT_CUSTOMER_SUMMARY_MONTHLY' AS TABNAME, COUNT(*) AS CNT FROM FACT_CUSTOMER_SUMMARY_MONTHLY
UNION
SELECT 'FACT_TRANSACTION' AS TABNAME, COUNT(*) AS CNT FROM FACT_TRANSACTION
UNION
SELECT 'RC_RULE_RESULTS' AS TABNAME, COUNT(*) AS CNT FROM RC_RULE_RESULTS
) T1
ORDER BY TABNAME; 
