DROP TABLE DIM_ADDRESS;
CREATE TABLE DIM_ADDRESS(	
	ADDRESS_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	SRC_ADDRESS_ID VARCHAR(50),
	ADDRESS_LINE1 VARCHAR(50),
	ADDRESS_LINE2 VARCHAR(50),
	ADDRESS_LINE3 VARCHAR(50),
	CITY VARCHAR(100),
	COUNTY VARCHAR(100),
	STATE VARCHAR(100),
	ZIPCODE INTEGER(10),
	COUNTRY VARCHAR(100),
	LATITUDE VARCHAR(50),
	LONGTITUDE VARCHAR(50),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT ADDRESS_ID_PK  PRIMARY KEY(ADDRESS_ID,LOAD_DATE,LOAD_ID),
CONSTRAINT SRC_ADDRESS_ID_UK  UNIQUE (SRC_ADDRESS_ID,LOAD_DATE,LOAD_ID));
 ALTER TABLE DIM_ADDRESS PARTITION BY KEY(LOAD_DATE,LOAD_ID);