DROP TABLE DIM_COUNTRY;
CREATE TABLE DIM_COUNTRY(	
	COUNTRY_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	COUNTRY_CODE VARCHAR(10),
	COUNTRY_NAME VARCHAR(100),
	COUNTRY_POPULATION INTEGER(10),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT COUNTRY_ID_PK  PRIMARY KEY(COUNTRY_ID,LOAD_DATE,LOAD_ID));
ALTER TABLE DIM_COUNTRY PARTITION BY KEY(LOAD_DATE,LOAD_ID);
