DROP TABLE DIM_CUSTOMER;
CREATE TABLE DIM_CUSTOMER(	
	CUSTOMER_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	SRC_CUSTOMER_ID VARCHAR(50),
	TITLE VARCHAR(100),
	FIRST_NAME VARCHAR(100),
	MIDDLE_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	ADDRESS_LINE1 VARCHAR(50),
	ADDRESS_LINE2 VARCHAR(50),
	PHONE VARCHAR(50),
	DATE_FIRST_PURCHASE VARCHAR(10),
	COMMUTE_DISTANCE INTEGER(10),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	POSTAL_CODE VARCHAR(10),
	COUNTRY VARCHAR(100),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT CUSTOMER_ID_PK  PRIMARY KEY(CUSTOMER_ID,LOAD_DATE,LOAD_ID));
ALTER TABLE DIM_CUSTOMER PARTITION BY KEY(LOAD_DATE,LOAD_ID);
