DROP TABLE DIM_BRANCH;
CREATE TABLE DIM_BRANCH(	
	BRANCH_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	SRC_BRANCH_ID VARCHAR(50),
	BRANCH_TYPE_CODE VARCHAR(10),
	BRANCH_NAME VARCHAR(100),
	BRANCH_DESC VARCHAR(500),
	BRANCH_CONTACT_NAME VARCHAR(100),
	BRANCH_CONTACT_PHONE VARCHAR(100),
	BRANCH_CONTACT_EMAIL VARCHAR(100),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT BRANCH_ID_PK  PRIMARY KEY(BRANCH_ID,LOAD_DATE,LOAD_ID),
CONSTRAINT SRC_BRANCH_ID_UK  UNIQUE (SRC_BRANCH_ID,LOAD_DATE,LOAD_ID));
 ALTER TABLE DIM_BRANCH PARTITION BY KEY(LOAD_DATE,LOAD_ID);