DROP TABLE IF EXISTS DIM_COUNTRY;
CREATE TABLE DIM_COUNTRY(	
	COUNTRY_CODE VARCHAR(10),
	COUNTRY_NAME VARCHAR(100),
	COUNTRY_POPULATION INTEGER(10), 
    COUNTRY_RISK_LEVEL INTEGER(50),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50));
