drop table if exists dim_account;
create table dim_account(	
	account_id varchar(50) default 0 not null,
	src_account_id varchar(50),
	account_type_code varchar(10),
	account_status_code varchar(10),
	product_type_code varchar(10),
	pin_number integer(10),
	nationality varchar(100),
	primary_iden_doc varchar(100),
	primary_iden_doc_id varchar(50),
	secondary_iden_doc varchar(100),
	secondary_iden_doc_id varchar(50),
	account_open_date varchar(10),
	account_number varchar(50),
	opening_balance integer(20),
	current_balance integer(20),
	overdue_balance integer(20),
	overdue_date varchar(10),
	currency_code varchar(10),
	interest_type varchar(50),
	interest_rate decimal(10,2),
        customer_id varchar(50),
	load_date varchar(10),
	load_id integer(50), 
constraint account_id_pk primary key(account_id));
