DROP TABLE FACT_ACCOUNT_SUMMARY_MONTHLY;
CREATE TABLE FACT_ACCOUNT_SUMMARY_MONTHLY(	
	ACCOUNT_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	YYYY_MM VARCHAR(50) DEFAULT 0 NOT NULL,
	TOTAL_TRANS_COUNT INTEGER(10),
	TOTAL_TRANS_AMOUNT_USD INTEGER(10),
	AVG_TRANS_AMOUNT INTEGER(10),
	MIN_AMOUNT DECIMAL(10,2),
	MAX_AMOUNT INTEGER(10),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT ACCOUNT_ID_PK  PRIMARY KEY(ACCOUNT_ID,LOAD_DATE,LOAD_ID));
ALTER TABLE FACT_ACCOUNT_SUMMARY_MONTHLY PARTITION BY KEY(LOAD_DATE,LOAD_ID);

