truncate table dim_account;
truncate table dim_address;
truncate table dim_bank;
truncate table dim_branch; 
truncate table dim_country;
truncate table dim_customer;
truncate table dim_state;
truncate table dim_transaction_type;
truncate table dp_rule_results;
truncate table dq_rule_results;
truncate table fact_account_summary_monthly;
truncate table fact_customer_summary_monthly;
truncate table fact_transaction;
truncate table rc_rule_results;


load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/account.csv' ignore into table account_mysql fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/account.csv' ignore into table account fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/account_status_type.csv' ignore into table account_status_type fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/account_type.csv' ignore into table account_type fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/address.csv' ignore into table address fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/bank.csv' ignore into table bank fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/branch.csv' ignore into table branch fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/branch_type.csv' ignore into table branch_type fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/dim_country.csv' ignore into table dim_country fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/customer.csv' ignore into table customer fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/dim_state.csv' ignore into table dim_state fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\r' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/dim_date.csv' ignore into table dim_date fields terminated by ',' enclosed by '"'   lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/product_type.csv' ignore into table product_type fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/transaction.csv' ignore into table transaction fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
load data local infile '/user/hive/warehouse/framework/app/edw/data/csv/header/transaction_type.csv' ignore into table transaction_type fields terminated by ',' enclosed by '"' escaped by '"' lines terminated by '\n' ignore 1 lines;
