DROP TABLE IF EXISTS PRODUCT_TYPE;
CREATE TABLE PRODUCT_TYPE(	
	PRODUCT_TYPE_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	PRODUCT_TYPE_CODE VARCHAR(10),
	PRODUCT_TYPE_DESC VARCHAR(500),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY(PRODUCT_TYPE_ID));