DROP TABLE PRODUCT_TYPE;
CREATE TABLE PRODUCT_TYPE(	
	PRODUCT_TYPE_ID VARCHAR(50) DEFAULT 0 NOT NULL,
	PRODUCT_TYPE_CODE VARCHAR(10),
	PRODUCT_TYPE_DESC VARCHAR(500),
	LOAD_DATE VARCHAR(10),
	LOAD_ID INTEGER(50), 
CONSTRAINT LOAD_ID_PK  PRIMARY KEY(PRODUCT_TYPE_ID,LOAD_DATE,LOAD_ID));
ALTER TABLE PRODUCT_TYPE PARTITION BY KEY(LOAD_DATE,LOAD_ID);
