package com.inferyx.framework.ws.client.disource;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-12T07:17:56.097+05:30
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "IngestServiceService",
                  wsdlLocation = "http://localhost:9000/Ingest?wsdl",
                  targetNamespace = "http://ingestion.ws.com/")
public class IngestServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ingestion.ws.com/", "IngestServiceService");
    public final static QName IngestServicePort = new QName("http://ingestion.ws.com/", "IngestServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9000/Ingest?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IngestServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9000/Ingest?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IngestServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IngestServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IngestServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IngestServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IngestServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IngestServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IngestService
     */
    @WebEndpoint(name = "IngestServicePort")
    public IngestService getIngestServicePort() {
        return super.getPort(IngestServicePort, IngestService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IngestService
     */
    @WebEndpoint(name = "IngestServicePort")
    public IngestService getIngestServicePort(WebServiceFeature... features) {
        return super.getPort(IngestServicePort, IngestService.class, features);
    }

}
