
package com.inferyx.framework.ws.client.disource;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-12T07:17:55.785+05:30
 * Generated source version: 3.3.1
 *
 */
public final class IngestService_IngestServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ingestion.ws.com/", "IngestServiceService");

    private IngestService_IngestServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IngestServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        IngestServiceService ss = new IngestServiceService(wsdlURL, SERVICE_NAME);
        IngestService port = ss.getIngestServicePort();

        {
        System.out.println("Invoking stream...");
        java.util.List<java.lang.String> _stream__return = port.stream();
        System.out.println("stream.result=" + _stream__return);


        }

        System.exit(0);
    }

}
