package com.inferyx.framework.ws.client.disource;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-12T07:17:56.055+05:30
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://ingestion.ws.com/", name = "IngestService")
@XmlSeeAlso({ObjectFactory.class})
public interface IngestService {

    @WebMethod
    @RequestWrapper(localName = "stream", targetNamespace = "http://ingestion.ws.com/", className = "com.inferyx.framework.ws.client.disource.Stream")
    @ResponseWrapper(localName = "streamResponse", targetNamespace = "http://ingestion.ws.com/", className = "com.inferyx.framework.ws.client.disource.StreamResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> stream();
}
