truncate table customer_es_allocation;
truncate table customer_generate_data;
truncate table customer_idiosyncratic_risk;
truncate table customer_idiosyncratic_transpose_stage;
truncate table customer_idiosyncratic_transpose;
truncate table customer_loss_simulation;
truncate table customer_portfolio_clone;
truncate table customer_portfolio_ul_calc_allocation;
truncate table customer_portfolio_ul_calc_summary;
truncate table customer_portfolio_ul_calc;
truncate table customer_portfolio_ul;
truncate table customer_portfolio;
truncate table customer_var_contribution_topn_perc;
truncate table industry_factor_correlation_transpose;
truncate table industry_factor_correlation;
truncate table industry_factor_mean;
truncate table industry_factor_simulation_stage;
truncate table industry_factor_simulation;
truncate table industry_factor_transpose;
truncate table lkp_reporting_date;
truncate table portfolio_expected_sum;
truncate table portfolio_loss_aggr_es;
truncate table portfolio_loss_histogram_percentage;
truncate table portfolio_loss_histogram;
truncate table portfolio_loss_simulation_aggr;
truncate table portfolio_loss_simulation_el;
truncate table portfolio_loss_simulation;
truncate table portfolio_loss_summary;
truncate table portfolio_var_heatmap_buckets;

sqlldr ecocap_small/ecocap_small /data/controlFilesOracle/customer_portfolio.ctl
sqlldr ecocap_small/ecocap_small /data/controlFilesOracle/industry_factor_correlation_transpose.ctl
sqlldr ecocap_small/ecocap_small /data/controlFilesOracle/industry_factor_correlation.ctl
sqlldr ecocap_small/ecocap_small /data/controlFilesOracle/industry_factor_mean.ctl
sqlldr ecocap_small/ecocap_small /data/controlFilesOracle/lkp_reporting_date.ctl
sqlldr ecocap_small/ecocap_small /data/controlFilesOracle/portfolio_var_heatmap_buckets.ctl








