DROP TABLE IF EXISTS DIM_COUNTRY; 

CREATE TABLE DIM_COUNTRY 
  ( 
     COUNTRY_CODE       STRING, 
     COUNTRY_NAME       STRING, 
     COUNTRY_POPULATION INT, 
     COUNTRY_RISK_LEVEL INT
  ) PARTITIONED BY (LOAD_DATE STRING, LOAD_ID STRING) ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',';
