CREATE TABLE "XE"."ACCOUNT" 
   (	"ACCOUNT_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"ACCOUNT_TYPE_ID" NUMBER(30,0), 
	"ACCOUNT_STATUS_ID" NUMBER(30,0), 
	"PRODUCT_TYPE_ID" NUMBER(30,0), 
	"CUSTOMER_ID" VARCHAR2(70 BYTE), 
	"PIN_NUMBER" NUMBER(30,0), 
	"NATIONALITY" VARCHAR2(70 BYTE), 
	"PRIMARY_IDEN_DOC" VARCHAR2(70 BYTE), 
	"PRIMARY_IDEN_DOC_ID" VARCHAR2(70 BYTE), 
	"SECONDARY_IDEN_DOC" VARCHAR2(70 BYTE), 
	"SECONDARY_IDEN_DOC_ID" VARCHAR2(70 BYTE), 
	"ACCOUNT_OPEN_DATE" VARCHAR2(70 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(70 BYTE), 
	"OPENING_BALANCE" VARCHAR2(70 BYTE), 
	"CURRENT_BALANCE" VARCHAR2(70 BYTE), 
	"OVERDUE_BALANCE" NUMBER(30,0), 
	"OVERDUE_DATE" VARCHAR2(70 BYTE), 
	"CURRENCY_CODE" VARCHAR2(70 BYTE), 
	"INTEREST_TYPE" VARCHAR2(70 BYTE), 
	"INTEREST_RATE" FLOAT(50), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(70 BYTE), 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ACCOUNT_ID", "LOAD_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) ) 


exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/ACCOUNT.ctl
   
   
   
   
   
   
   
   
   
