
  CREATE TABLE "XE"."ADDRESS" 
   (	"ADDRESS_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"ADDRESS_LINE1" VARCHAR2(70 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(70 BYTE), 
	"ADDRESS_LINE3" VARCHAR2(70 BYTE), 
	"CITY" VARCHAR2(70 BYTE), 
	"COUNTY" VARCHAR2(70 BYTE), 
	"STATE" VARCHAR2(70 BYTE), 
	"ZIPCODE" NUMBER(30,0), 
	"COUNTRY" VARCHAR2(70 BYTE), 
	"LATITUDE" VARCHAR2(70 BYTE), 
	"LONGITUDE" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"VERSION" NUMBER(30,0), 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID", "LOAD_DATE") DISABLE
   ) PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )


exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/ADDRESS.ctl
