
  CREATE TABLE "XE"."BANK" 
   (	"BANK_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"BANK_CODE" VARCHAR2(70 BYTE), 
	"BANK_NAME" VARCHAR2(70 BYTE), 
	"BANK_ACCOUNT_NUMBER" VARCHAR2(70 BYTE), 
	"BANK_CURRENCY_CODE" VARCHAR2(70 BYTE), 
	"BANK_CHECK_DIGITS" NUMBER(30,0), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"VERSION" NUMBER(30,0), 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "BANK_PK" PRIMARY KEY ("BANK_ID", "LOAD_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )


exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/BANK.ctl
