
  CREATE TABLE "XE"."CUSTOMER" 
   (	"CUSTOMER_ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"ADDRESS_ID" VARCHAR2(70 BYTE), 
	"BRANCH_ID" NUMBER(30,0), 
	"TITLE" VARCHAR2(70 BYTE), 
	"FIRST_NAME" VARCHAR2(70 BYTE), 
	"MIDDLE_NAME" VARCHAR2(70 BYTE), 
	"LAST_NAME" VARCHAR2(70 BYTE), 
	"SSN" VARCHAR2(70 BYTE), 
	"PHONE" VARCHAR2(70 BYTE), 
	"DATE_FIRST_PURCHASE" VARCHAR2(70 BYTE), 
	"COMMUTE_DISTANCE_MILES" NUMBER(30,0), 
	"LOAD_DATE" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"VERSION" NUMBER(30,0), 
	"LOAD_ID" NUMBER(30,0), 
	 CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID", "LOAD_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )



exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/CUSTOMER.ctl
