
  CREATE TABLE "XE"."TRANSACTION_TYPE" 
   (	"TRANSACTION_TYPE_ID" VARCHAR2(70 BYTE), 
	"TRANSACTION_TYPE_CODE" VARCHAR2(70 BYTE), 
	"TRANSACTION_TYPE_DESC" VARCHAR2(70 BYTE), 
	"LOAD_DATE" VARCHAR2(70 BYTE), 
	"VERSION" NUMBER(30,0), 
	"LOAD_ID" NUMBER(30,0)
   )PARTITION BY RANGE (LOAD_DATE,LOAD_ID) 
 (PARTITION PARTITION_NAME  VALUES LESS THAN (MAXVALUE, MAXVALUE) )


exit

su oracle

sqlldr xe/admin /opt/oracle/app/controlLoadFile/TRANSACTION_TYPE.ctl
