
DROP TABLE ecocap.customer_idiosyncratic_risk;

CREATE TABLE ecocap.customer_idiosyncratic_risk (

   iteration_id    integer ,
   cust1    double  precision ,
   cust2    double  precision ,
   cust3    double  precision ,
   cust4    double  precision ,
   cust5    double  precision ,
   cust6    double  precision ,
   cust7    double  precision ,
   cust8    double  precision ,
   cust9    double  precision ,
   cust10   double  precision ,
   cust11   double  precision ,
   cust12   double  precision ,
   cust13   double  precision ,
   cust14   double  precision ,
   cust15   double  precision ,
   cust16   double  precision ,
   cust17   double  precision ,
   cust18   double  precision ,
   cust19   double  precision ,
   cust20   double  precision ,
   cust21   double  precision ,
   cust22   double  precision ,
   cust23   double  precision ,
   cust24   double  precision ,
   cust25   double  precision ,
   cust26   double  precision ,
   cust27   double  precision ,
   cust28   double  precision ,
   cust29   double  precision ,
   cust30   double  precision ,
   cust31   double  precision ,
   cust32   double  precision ,
   cust33   double  precision ,
   cust34   double  precision ,
   cust35   double  precision ,
   cust36   double  precision ,
   cust37   double  precision ,
   cust38   double  precision ,
   cust39   double  precision ,
   cust40   double  precision ,
   cust41   double  precision ,
   cust42   double  precision ,
   cust43   double  precision ,
   cust44   double  precision ,
   cust45   double  precision ,
   cust46   double  precision ,
   cust47   double  precision ,
   cust48   double  precision ,
   cust49   double  precision ,
   cust50   double  precision ,
   cust51   double  precision ,
   cust52   double  precision ,
   cust53   double  precision ,
   cust54   double  precision ,
   cust55   double  precision ,
   cust56   double  precision ,
   cust57   double  precision ,
   cust58   double  precision ,
   cust59   double  precision ,
   cust60   double  precision ,
   cust61   double  precision ,
   cust62   double  precision ,
   cust63   double  precision ,
   cust64   double  precision ,
   cust65   double  precision ,
   cust66   double  precision ,
   cust68   double  precision ,
   cust69   double  precision ,
   cust70   double  precision ,
   cust71   double  precision ,
   cust72   double  precision ,
   cust73   double  precision ,
   cust74   double  precision ,
   cust75   double  precision ,
   cust76   double  precision ,
   cust77   double  precision ,
   cust78   double  precision ,
   cust79   double  precision ,
   cust80   double  precision ,
   cust81   double  precision ,
   cust82   double  precision ,
   cust83   double  precision ,
   cust84   double  precision ,
   cust85   double  precision ,
   cust86   double  precision ,
   cust87   double  precision ,
   cust88   double  precision ,
   cust89   double  precision ,
   cust90   double  precision ,
   cust91   double  precision ,
   cust92   double  precision ,
   cust93   double  precision ,
   cust94   double  precision ,
   cust95   double  precision ,
   cust96   double  precision ,
   reporting_date   text,
   version    integer);





