
drop table if exists device_data_categorical_features;
create table device_data_categorical_features
(
deviceid  varchar(50), 
 date  varchar(50), 
 cat1  varchar(50), 
 cat2  varchar(50), 
 cat3  varchar(50), 
 cat4  varchar(50), 
 fault_code_type_1_count_category  varchar(50), 
 fault_code_type_1_count_per_usage1_category  varchar(50), 
 fault_code_type_1_count_per_usage2_category  varchar(50), 
 fault_code_type_2_count_category  varchar(50), 
 fault_code_type_2_count_per_usage1_category  varchar(50), 
 fault_code_type_2_count_per_usage2_category  varchar(50), 
 fault_code_type_3_count_category  varchar(50), 
 fault_code_type_3_count_per_usage1_category  varchar(50), 
 fault_code_type_3_count_per_usage2_category  varchar(50), 
 fault_code_type_4_count_category  varchar(50), 
 fault_code_type_4_count_per_usage1_category  varchar(50), 
 fault_code_type_4_count_per_usage2_category  varchar(50), 
 problem_type_1_category  varchar(50), 
 problem_type_1_per_usage1_category  varchar(50), 
 problem_type_1_per_usage2_category  varchar(50), 
 problem_type_2_category  varchar(50), 
 problem_type_2_per_usage1_category  varchar(50), 
 problem_type_2_per_usage2_category  varchar(50), 
 problem_type_3_category  varchar(50), 
 problem_type_3_per_usage1_category  varchar(50), 
 problem_type_3_per_usage2_category  varchar(50), 
 problem_type_4_category  varchar(50), 
 problem_type_4_per_usage1_category  varchar(50), 
 problem_type_4_per_usage2_category  varchar(50), 
 version   integer(50));
